# Generated by Django 3.0.2 on 2020-02-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjuice', '0003_auto_20200201_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain_name',
        ),
        migrations.AddField(
            model_name='domain',
            name='code',
            field=models.CharField(default='code', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='name',
            field=models.CharField(default='code', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
