# Generated by Django 3.0.2 on 2020-02-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjuice', '0005_auto_20200203_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='topic',
            name='code',
            field=models.CharField(default='asd', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='asd', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
