# Generated by Django 3.0.2 on 2020-02-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjuice', '0006_auto_20200203_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='overview',
            field=models.TextField(default='topic overview', max_length=500),
            preserve_default=False,
        ),
    ]
