# Generated by Django 3.0.2 on 2020-02-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjuice', '0007_topic_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('topics', models.ManyToManyField(to='openjuice.Topic')),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
