# Generated by Django 3.0.2 on 2020-02-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjuice', '0009_courseresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookresource',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
